---
apiVersion: v1
kind: Deployment
metadata:
  namespace: upstream1
  labels:
    app: nginx2
  name: nginx2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx2
  dnsPolicy: ClusterFirst
  restartPolicy: Always